version: "3.5"

networks:
  openstates-network:
      name: openstates-network

services:
  django:
    build:
      context: .
      dockerfile: docker/uwsgi/Dockerfile
    volumes:
      - .:/code
    environment:
      # dev settings to reload python files when edited
      - UWSGI_PYTHON_AUTORELOAD=3
      - UWSGI_ENABLE_THREADS=1
      - DEBUG
      - SECRET_KEY
      - DATABASE_URL=postgis://openstates:openstates@db/openstatesorg
    ports:
      - "7000:7000"
    networks:
      - openstates-network
