version: "3.5"

networks:
  openstates-network:
      name: openstates-network

services:
  api:
    build:
      context: .
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://openstates:openstates@db/openstatesorg
      - RRL_REDIS_HOST=redis
    ports:
      - "7000:8000"
    networks:
      - openstates-network
    command:
      - poetry
      - run
      - uvicorn
      - api.main:app
      - --host=0.0.0.0
  redis:
    image: redis
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - openstates-network
