version: "3.5"

networks:
  openstates-network:
      name: openstates-network

services:
  api:
    build:
      context: .
    volumes:
      - .:/code
    environment:
      - DATABASE_URL=postgis://openstates:openstates@db/openstatesorg
    ports:
      - "7000:80"
    networks:
      - openstates-network
