[tool.poetry]
name = "openstates-api"
version = "0.1.0"
description = "Future Open States API"
authors = ["James Turk <james@openstates.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
fastapi = {extras = ["all"], version = "^0.61.0"}
openstates_metadata = "^2020.4.7"
sqlalchemy = "^1.3.18"
psycopg2-binary = "^2.8.5"
pytest = "^6.0.1"
sqlalchemy_utils = "^0.36.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
