[tool.poetry]
name = "simpleapi"
version = "0.1.0"
description = ""
authors = ["James Turk <james@openstates.org>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
openstates-metadata = "^2020.4.7"
openstates = "^4.7"
django = "^3.0.5"
sentry-sdk = "^0.16.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
