# This is a basic workflow to help you get started with Actions

name: Build and push Docker images
on:
  push:
    branches: [ master ]
jobs: 
  publish:
    steps: 
      - name: build docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: openstates/simpleapi
          dockerfile: docker/uwsgi/Dockerfile
          tags: latest
    runs-on: ubuntu-18.04
