name: Build and push Docker images
on:
  push:
    branches:
      - main
    tags:
      - '*'
jobs:
  publish:
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build docker image
        uses: docker/build-push-action@3
        with:
          dockerfile: /github/workspace/Dockerfile
          tag_with_ref: true
          tags: openstates/api-v3:latest
          platforms: amd64,arm64
    runs-on: ubuntu-latest
